ADDON_KEY = "TLFC_EDITOR_HANDLE"
INFO_ADDON_KEY = "TLFC_INFO_EDITOR_HANDLE"
EDITOR_UI_KEY = "TLFC_EDITOR_UI"
ENABLED_AREAS_KEY = "TLFC_ENABLED_AREAS"
PRESET_FILE = "curve_presets.txt"

HANDLE_HIT_RADIUS_PX = 20
SIDEBAR_EDGE_HIT_PX = 6

REDRAW_LOAD_EWMA_KEY = "TLFC_REDRAW_LOAD_EWMA"
REDRAW_LAST_TICK_KEY = "TLFC_REDRAW_LAST_TICK"
REDRAW_LAST_INTERVAL_KEY = "TLFC_REDRAW_LAST_INTERVAL"
MODAL_SESSION_KEY = "TLFC_MODAL_SESSION"
SWITCH_BLOCK_UNTIL_KEY = "TLFC_SWITCH_BLOCK_UNTIL"
